In [1]:
import numpy as np

# Sklearn 的Standardscaler

In [2]:
import sklearn 
from sklearn.preprocessing import StandardScaler

In [3]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()

In [4]:
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [5]:
print(scaler.mean_)

[0.5 0.5]


In [6]:
print(scaler.transform(data))

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [7]:
print(scaler.transform([[2, 2]]))

[[3. 3.]]


# Mystandardscaler

In [8]:
class Mystandardscaler():
    def _init_(self):
        self.mean_ = None
        self.std_ = None
        
    def fit(self, x):
        self.mean_ = np.mean(x,axis=0)
        self.std_ = np.std(x, axis=0)
        
    def transform(self, x):
        return (x-self.mean_)/self.std_
    
    def fit_transform(self,x):
        self.fit(x)
        return self.transform(x)

In [9]:
Myscaler=Mystandardscaler()

In [10]:
Myscaler.fit(data)

In [11]:
Myscaler.mean_

array([0.5, 0.5])

In [12]:
Myscaler.std_

array([0.5, 0.5])

In [13]:
Myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [14]:
scaler.transform([[2, 2]])

array([[3., 3.]])